language: go

sudo: false

go: 
    - 1.11.x

before_install:
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover

script:
    - GOOS=darwin go build
    - GOOS=windows go build
    - GOOS=linux go build
    - $GOPATH/bin/goveralls -service=travis-ci