language: go

sudo: false

go: 
    - master

before_install:
    - go get github.com/mattn/goveralls
    - go get github.com/voidint/gbb

script:
    - GOOS=darwin gbb --debug -a
    - GOOS=windows gbb --debug -a
    - GOOS=linux gbb --debug -a
    - go test -v ./...
    - $GOPATH/bin/goveralls -service=travis-ci